### PR TITLE
Update tsconfig.json - add packages/contracts

### LINKED ISSUE #1006: `npx gsn relayer-register` breaks on `@opengsn/cli@3.0.0-beta.10`
**Describe the bug**
Running `npx gsn relayer-register` ends up breaking:

`Error: Cannot find module '@opengsn/contracts/types/ethers-contracts'`

Using:

`"@opengsn/cli": "3.0.0-beta.10"`

**Steps To Reproduce**
1. Install @opengsn/cli@3.0.0-beta.10
2. Run `npx gsn relayer-register` with your config
3. See that script breaks

**Expected behavior**
Should run without breaking

**Console Logs and/or Screenshots**
image

**Disclaimer:** this is a testnet env pic so no issues with sharing the private key

### PR DESCRIPTION
**Pull request by qq7**
without this line, running `gsn deploy` fails with `Error: Cannot find module '@opengsn/contracts/types/ethers-contracts'`
closes https://github.com/opengsn/gsn/issues/1006

### CODE REVIEW

**Review by forshtat — APPROVED** [review]

**Comment by forshtat** [comment]
> without this line, running `gsn deploy` fails with `Error: Cannot find module '@opengsn/contracts/types/ethers-contracts'` closes #1006

Unfortunately it appears that `truffle` is not able to install the solidity compiler any more, and given that `truffle` has been deprecated it is likely more things will break as well. So unless you can also fix this issue, merging this PR will not be useful until the migration to current frameworks is complete (https://github.com/opengsn/gsn/pull/1012).

**Comment by qq7** [comment]
@forshtat 
> Unfortunately it appears that `truffle` is not able to install the solidity compiler any more

Ahh, I didn't check with 0.8.7... It compiled fine on my machine when I bumped solc version to 0.8.15. Let's give it a go on CircleCI...

**Comment by qq7** [comment]
This time it has worked. Might also make sense to bump solc version in paymasters package.
